### ISSUE TITLE
Got errors in the log when trying example?

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#91] opened 2024-01-26 15:28 UTC
I get these errors in my log, when trying your example template

> [2024-01-26 16:22:16.090] [info]    Received message from 127.0.0.1: CG 1-20 ADD 0 "EXAMPLE" 1 "<templateData><componentData id=\"name\"><data id=\"text\" value=\"Tue Sandbæk\"/></componentData></templateData>"\r\n
[2024-01-26 16:22:16.090] [info]    Sent message to 127.0.0.1:202 CG OK\r\n
[2024-01-26 16:22:16.095] [info]    html[file://C:\casparcg-server-v2.3.3-lts-stable\template/EXAMPLE.html] Destroyed.
[2024-01-26 16:22:16.245] [info]    html[file://C:\casparcg-server-v2.3.3-lts-stable\template/EXAMPLE.html] 1920 1080 50.000000 Log: Qg.update({
[2024-01-26 16:22:16.245] [info]      "name": {
[2024-01-26 16:22:16.245] [info]        "text": "Tue Sandbæk"
[2024-01-26 16:22:16.245] [info]      }
[2024-01-26 16:22:16.245] [info]    })
[2024-01-26 16:22:16.245] [info]    html[file://C:\casparcg-server-v2.3.3-lts-stable\template/EXAMPLE.html] 1920 1080 50.000000 Log: Qg.play()
[2024-01-26 16:22:16.252] [error]   html[file://C:\casparcg-server-v2.3.3-lts-stable\template/EXAMPLE.html] 1920 1080 50.000000 Log: Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
[2024-01-26 16:22:16.252] [error]   html[file://C:\casparcg-server-v2.3.3-lts-stable\template/EXAMPLE.html] 1920 1080 50.000000 Log: Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

What do i miss?

**Comment by tobiasandersen** [comment] 2024-01-27 09:45
You're sending `name` as an object, but you probably want it to be a string? Or use `name.text` in your template?

**Comment by 7u5a** [comment] 2024-01-27 22:56
I was testing this
[example.zip](https://github.com/nxtedition/create-caspar-graphics/files/14074241/example.zip)
[example.zip](https://github.com/nxtedition/create-caspar-graphics/files/14074244/example.zip)
Did'nt change anything, just build it from your [create-caspar-graphics](https://github.com/nxtedition/create-caspar-graphics)

**Comment by 7u5a** [comment] 2024-01-27 23:41
By the way.
When I try to run this template with Caspar CG Client, I get these errors.
But when I do it with SuperConductor, there is no problem.
Why is that?

**Comment by tobiasandersen** [comment] 2024-01-28 14:30
The problem is how the data is sent. The template is expecting `name` to be a string, but you're sending an object that contains a property `text` (which is a string).

**Comment by 7u5a** [comment] 2024-01-28 20:41
I did'nt know, but I've found the error.
![image](https://github.com/nxtedition/create-caspar-graphics/assets/89579091/2df6af25-3dc6-4bda-b29a-ede2ce91015e)
Had to check this box...

**Comment by tobiasandersen** [comment] 2024-01-29 08:06
It could be that the XML parsing is wrong here, I've never used it myself. When you used that data (as seen on your last picture), but didn't click "Send as JSON", you got the problem you originally posted?

**Comment by 7u5a** [comment] 2024-02-07 00:44
yes @tobiasandersen it seems it is when sending data not as json.
If I need to be able to send data without json, is it then the template og is it the casparcg server?

**Comment by tobiasandersen** [comment] 2024-02-07 08:37
I think it should work better in `graphics-kit@2.0.0-alpha.24`

**Comment by 7u5a** [comment] 2024-02-07 23:26
And what’s that, and where to find it?

**Comment by tobiasandersen** [comment] 2024-02-08 08:24
I'm referring to this package: https://www.npmjs.com/package/@nxtedition/graphics-kit. I released an update yesterday where this should be fixed.

**Closed** 2024-09-05 21:16 UTC
